apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

commonAnnotations:
  environment: production
  owner: platform-engineering
  compliance: zero-trust-soc2

resources:
  - ../../base

images:
  - name: beyond-gravity/launch-events
    newName: ghcr.io/beyond-gravity/launch-events
    newTag: v1.4.2

replicas:
  - name: web
    count: 3
