apiVersion: v1
kind: Secret
metadata:
  name: launch-events-secret
type: Opaque
stringData:
  SECRET_KEY: "prod-insecure-k8s-secret-key-replace-with-kms-vault-engine"
  POSTGRES_PASSWORD: "production_db_secret"
